# Application Configuration
spring.application.name=Order Service
server.port=8080

# Logging Configuration
logging.level.root=INFO
logging.level.com.example.orders=DEBUG

#Data
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

#Management
management.endpoints.web.exposure.include=health,info
